### ISSUE TITLE
Library not loaded: libcaffe.so.1.0.0-rc3

### ISSUE THREAD

**Issue by Ha-Ham** [rbgirshick/caffe-fast-rcnn#21]
i am under mac os 10.12.3 Sierra .
when i run :  hamdihamed$ python /Users/hamdihamed/Desktop/py-faster-rcnn/tools/demo.py
i get this error 
Traceback (most recent call last):
  File "/Users/hamdihamed/Desktop/py-faster-rcnn/tools/demo.py", line 18, in <module>
    from fast_rcnn.test import im_detect
  File "/Users/hamdihamed/Desktop/py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 16, in <module>
    import caffe
  File "/Users/hamdihamed/Desktop/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/Users/hamdihamed/Desktop/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dlopen(/Users/hamdihamed/Desktop/py-faster-rcnn/tools/../caffe-fast-rcnn/python/caffe/_caffe.so, 2): Library not loaded: libcaffe.so.1.0.0-rc3
  Referenced from: /Users/hamdihamed/Desktop/py-faster-rcnn/caffe-fast-rcnn/python/caffe/_caffe.so
  Reason: image not found

any help ??

**Comment by fujingling** [comment]
Hi! did you solve this problem? I get the same error with you, if you solved it, can you tell me how did you do?Thank you very much

**Comment by Ha-Ham** [comment]
try to make pycaffe and install all the missing python libraries (pip install "library_name").
PS: you wont be able to train faster rcnn on CPU , unfortunately.
